language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - osx
before_script:
  - rustup target add x86_64-unknown-linux-gnu
notifications:
  email: false
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
